"""add totp field

Revision ID: 0d8d67c1190e
Revises: 8b954a157175
Create Date: 2021-03-17 23:01:16.805448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8d67c1190e'
down_revision = '8b954a157175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp_secret', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp_secret')
    # ### end Alembic commands ###
